/**
 * First Contact - A sample invasion scenario
 *
 * The alien fleet arrives in Earth orbit and begins systematic conquest.
 * This scenario spans the first 72 hours of the invasion.
 */

import type { Scenario } from '../game/types';

export const firstContactScenario: Scenario = {
  id: 'first-contact',
  name: 'First Contact',
  description: 'Day One of the invasion. The alien fleet emerges from behind the Moon and begins its assault on Earth.',

  events: [
    // === HOUR 0-1: ARRIVAL ===
    {
      id: 'arrival-1',
      time: 0,
      type: 'narrative',
      alienMessage: 'FLEET EMERGENCE COMPLETE. 47 VESSELS IN FORMATION.',
      newsHeadline: 'Massive objects detected emerging from lunar shadow',
      newsDetail: 'NASA and ESA confirm multiple large objects approaching Earth. Emergency briefings scheduled.',
      importance: 'critical',
    },
    {
      id: 'arrival-2',
      time: 0.25,
      type: 'narrative',
      alienMessage: 'INITIATING ORBITAL INSERTION. PRIMARY TARGETS IDENTIFIED.',
      newsHeadline: 'World leaders convene emergency summit',
      importance: 'major',
    },
    {
      id: 'arrival-3',
      time: 0.5,
      type: 'narrative',
      alienMessage: 'DEPLOYING RECONNAISSANCE SWARMS',
      newsHeadline: 'Strange lights reported across multiple continents',
      newsDetail: 'Social media flooded with reports of glowing objects in the sky.',
      importance: 'minor',
    },

    // === HOUR 1-2: FIRST STRIKES - COMMUNICATIONS ===
    {
      id: 'hack-comms-1',
      time: 1,
      type: 'hack',
      locationId: 'usa-nsa',
      alienMessage: 'TARGETING ENEMY SIGNALS INTELLIGENCE HUB',
      newsHeadline: 'Major internet outages reported across Eastern US',
      newsDetail: 'Pentagon confirms "cyber incident" affecting military networks.',
      importance: 'major',
      focusCamera: true,
      effect: {
        locationId: 'usa-nsa',
        newStatus: 'targeted',
      },
    },
    {
      id: 'hack-comms-2',
      time: 1.25,
      type: 'hack',
      locationId: 'uk-gchq',
      alienMessage: 'DISRUPTING ATLANTIC COMMAND LINKS',
      newsHeadline: 'UK government communications compromised',
      importance: 'major',
      effect: {
        locationId: 'uk-gchq',
        newStatus: 'targeted',
      },
    },
    {
      id: 'hack-comms-3',
      time: 1.5,
      type: 'hack',
      locationId: 'australia-pinegap',
      alienMessage: 'NEUTRALIZING PACIFIC SURVEILLANCE NODE',
      newsHeadline: 'Australian intelligence facility reports systems failure',
      importance: 'minor',
      effect: {
        locationId: 'australia-pinegap',
        newStatus: 'targeted',
      },
    },
    {
      id: 'hack-comms-4',
      time: 1.75,
      type: 'hack',
      locationId: 'china-korla',
      alienMessage: 'DISABLING CHINESE INTELLIGENCE ARRAY',
      newsHeadline: 'Chinese military networks go dark',
      importance: 'major',
      effect: {
        locationId: 'china-korla',
        newStatus: 'targeted',
      },
    },

    // === HOUR 2-4: DISABLE AIR DEFENSES ===
    {
      id: 'attack-norad',
      time: 2,
      type: 'attack',
      locationId: 'usa-norad',
      alienMessage: 'PRIORITY TARGET: NORAD COMMAND CENTER',
      newsHeadline: 'BREAKING: Cheyenne Mountain under attack',
      newsDetail: 'Witnesses report massive explosions near Colorado Springs. All civilian aircraft grounded.',
      importance: 'critical',
      focusCamera: true,
      effect: {
        locationId: 'usa-norad',
        newStatus: 'contested',
        stabilityChange: -30,
      },
    },
    {
      id: 'attack-pentagon',
      time: 2.25,
      type: 'attack',
      locationId: 'usa-pentagon',
      alienMessage: 'STRIKING ENEMY COMMAND HEADQUARTERS',
      newsHeadline: 'Pentagon hit by orbital strike',
      newsDetail: 'Kinetic bombardment impacts reported at the Pentagon. Casualties unknown.',
      importance: 'critical',
      effect: {
        locationId: 'usa-pentagon',
        newStatus: 'contested',
        stabilityChange: -20,
      },
    },
    {
      id: 'attack-response-1',
      time: 2.5,
      type: 'human_response',
      alienMessage: 'DETECTING ENEMY AIRCRAFT SCRAMBLE. INSIGNIFICANT.',
      newsHeadline: 'US Air Force scrambles fighters nationwide',
      newsDetail: 'F-22s and F-35s deployed from multiple bases.',
      importance: 'major',
    },
    {
      id: 'attack-ramstein',
      time: 2.75,
      type: 'attack',
      locationId: 'usa-ramstein',
      alienMessage: 'SUPPRESSING NATO AIR OPERATIONS',
      newsHeadline: 'Ramstein Air Base under heavy bombardment',
      newsDetail: 'German authorities confirm hostile action at major NATO installation.',
      importance: 'critical',
      effect: {
        locationId: 'usa-ramstein',
        newStatus: 'contested',
        stabilityChange: -40,
      },
    },
    {
      id: 'attack-russia-cmd',
      time: 3,
      type: 'attack',
      locationId: 'russia-command',
      alienMessage: 'NEUTRALIZING RUSSIAN STRATEGIC COMMAND',
      newsHeadline: 'Russian Strategic Command under attack',
      newsDetail: 'Reports of explosions at Russia\'s main nuclear command facility.',
      importance: 'critical',
      effect: {
        locationId: 'russia-command',
        newStatus: 'contested',
        stabilityChange: -30,
      },
    },
    {
      id: 'destroy-fighters',
      time: 3.5,
      type: 'destroy',
      locationId: 'usa-norfolk',
      alienMessage: 'ENEMY AIRCRAFT AND NAVAL ASSETS NEUTRALIZED. 47 UNITS ELIMINATED.',
      newsHeadline: 'Norfolk Naval Station struck from orbit',
      newsDetail: 'US Navy\'s largest base reports devastating losses. Aircraft carrier USS Ford destroyed in port.',
      importance: 'critical',
      effect: {
        locationId: 'usa-norfolk',
        newStatus: 'neutralized',
        newControlledBy: 'destroyed',
      },
    },

    // === HOUR 4-6: POWER GRID AND INFRASTRUCTURE ===
    {
      id: 'attack-grid-1',
      time: 4,
      type: 'destroy',
      locationId: 'usa-threemile',
      alienMessage: 'INITIATING INFRASTRUCTURE DISRUPTION PROTOCOL',
      newsHeadline: 'Three Mile Island power complex destroyed',
      newsDetail: 'Massive power outages spreading across Northeast. Containment fears.',
      importance: 'critical',
      focusCamera: true,
      effect: {
        locationId: 'usa-threemile',
        newStatus: 'neutralized',
        newControlledBy: 'destroyed',
      },
    },
    {
      id: 'attack-grid-2',
      time: 4.5,
      type: 'attack',
      locationId: 'france-tricastin',
      alienMessage: 'EUROPEAN POWER GRID: TARGETING NODE',
      newsHeadline: 'French nuclear plant hit',
      newsDetail: 'Tricastin nuclear complex struck. France declares state of emergency.',
      importance: 'major',
      effect: {
        locationId: 'france-tricastin',
        newStatus: 'neutralized',
        newControlledBy: 'destroyed',
      },
    },
    {
      id: 'civilian-panic-1',
      time: 4.75,
      type: 'civilian',
      alienMessage: 'CIVILIAN POPULATION EXHIBITING EXPECTED DISORGANIZATION',
      newsHeadline: 'Mass evacuations begin in major cities',
      newsDetail: 'Highways gridlocked as millions flee urban centers.',
      importance: 'major',
    },
    {
      id: 'attack-pearl',
      time: 5,
      type: 'attack',
      locationId: 'usa-pearlharbor',
      alienMessage: 'PACIFIC FLEET ASSETS: SUPPRESSING',
      newsHeadline: 'Pearl Harbor under attack for second time in history',
      newsDetail: 'Pacific Fleet sustains heavy damage. Parallels to 1941 drawn.',
      importance: 'critical',
      focusCamera: true,
      effect: {
        locationId: 'usa-pearlharbor',
        newStatus: 'contested',
        stabilityChange: -20,
      },
    },
    {
      id: 'attack-sanya',
      time: 5.5,
      type: 'attack',
      locationId: 'china-sanya',
      alienMessage: 'CHINESE NAVAL ASSETS: NEUTRALIZING',
      newsHeadline: 'Chinese submarine base destroyed',
      newsDetail: 'Sanya naval facility on Hainan Island reportedly wiped out.',
      importance: 'major',
      effect: {
        locationId: 'china-sanya',
        newStatus: 'neutralized',
        newControlledBy: 'destroyed',
      },
    },

    // === HOUR 6-10: GLOBAL EXPANSION ===
    {
      id: 'attack-europe-1',
      time: 6,
      type: 'attack',
      locationId: 'uk-london',
      alienMessage: 'EUROPEAN THEATER: TARGETING UK COMMAND',
      newsHeadline: 'London under attack',
      newsDetail: 'Explosions reported across the capital. Royal Family evacuated.',
      importance: 'critical',
      focusCamera: true,
      effect: {
        locationId: 'uk-london',
        newStatus: 'contested',
        stabilityChange: -25,
      },
    },
    {
      id: 'attack-faslane',
      time: 6.5,
      type: 'destroy',
      locationId: 'uk-faslane',
      alienMessage: 'ELIMINATING UK NUCLEAR SUBMARINE CAPABILITY',
      newsHeadline: 'Faslane naval base destroyed',
      newsDetail: 'UK nuclear submarine base in Scotland hit. Trident capability feared lost.',
      importance: 'critical',
      effect: {
        locationId: 'uk-faslane',
        newStatus: 'neutralized',
        newControlledBy: 'destroyed',
      },
    },
    {
      id: 'attack-paris',
      time: 7,
      type: 'attack',
      locationId: 'france-paris',
      alienMessage: 'FRENCH SECTOR: NEUTRALIZING RESISTANCE',
      newsHeadline: 'Paris under bombardment',
      newsDetail: 'Eiffel Tower visible burning. French military retreating south.',
      importance: 'critical',
      focusCamera: true,
      effect: {
        locationId: 'france-paris',
        newStatus: 'contested',
        stabilityChange: -30,
      },
    },
    {
      id: 'attack-berlin',
      time: 7.5,
      type: 'attack',
      locationId: 'germany-berlin',
      alienMessage: 'GERMAN SECTOR: COMMAND ASSETS TARGETED',
      newsHeadline: 'Berlin struck by orbital weapons',
      newsDetail: 'Bundestag destroyed. German chancellor relocated to undisclosed location.',
      importance: 'major',
      effect: {
        locationId: 'germany-berlin',
        newStatus: 'contested',
        stabilityChange: -25,
      },
    },
    {
      id: 'attack-sevastopol',
      time: 8,
      type: 'attack',
      locationId: 'russia-sevastopol',
      alienMessage: 'BLACK SEA FLEET: NEUTRALIZED',
      newsHeadline: 'Russian Black Sea Fleet destroyed in port',
      newsDetail: 'Sevastopol naval base devastated by kinetic bombardment.',
      importance: 'major',
      effect: {
        locationId: 'russia-sevastopol',
        newStatus: 'neutralized',
        newControlledBy: 'destroyed',
      },
    },
    {
      id: 'attack-tokyo',
      time: 8.5,
      type: 'attack',
      locationId: 'japan-tokyo',
      alienMessage: 'PACIFIC THEATER: SECURING JAPANESE SECTOR',
      newsHeadline: 'Tokyo devastated by strikes',
      newsDetail: 'Japanese Self-Defense Forces overwhelmed. Emperor calls for calm.',
      importance: 'critical',
      focusCamera: true,
      effect: {
        locationId: 'japan-tokyo',
        newStatus: 'contested',
        stabilityChange: -35,
      },
    },
    {
      id: 'attack-seoul',
      time: 9,
      type: 'attack',
      locationId: 'southkorea-seoul',
      alienMessage: 'KOREAN PENINSULA: SUPPRESSING DEFENSES',
      newsHeadline: 'Seoul under alien attack',
      newsDetail: 'South Korean military in full retreat. US forces in Korea decimated.',
      importance: 'major',
      effect: {
        locationId: 'southkorea-seoul',
        newStatus: 'contested',
        stabilityChange: -30,
      },
    },
    {
      id: 'attack-diego',
      time: 9.5,
      type: 'destroy',
      locationId: 'usa-diegogarcia',
      alienMessage: 'INDIAN OCEAN STAGING BASE: ELIMINATED',
      newsHeadline: 'Diego Garcia military base obliterated',
      newsDetail: 'Remote US/UK military atoll in Indian Ocean destroyed. No survivors expected.',
      importance: 'major',
      effect: {
        locationId: 'usa-diegogarcia',
        newStatus: 'neutralized',
        newControlledBy: 'destroyed',
      },
    },

    // === HOUR 10-15: NUCLEAR RESPONSE AND COUNTER ===
    {
      id: 'human-nuclear-attempt',
      time: 10,
      type: 'human_response',
      alienMessage: 'DETECTING NUCLEAR LAUNCH PREPARATION. COUNTERMEASURES READY.',
      newsHeadline: 'DEFCON 1 declared',
      newsDetail: 'Multiple nations reportedly preparing nuclear response.',
      importance: 'critical',
    },
    {
      id: 'intercept-nukes',
      time: 11,
      type: 'destroy',
      locationId: 'usa-malmstrom',
      alienMessage: 'NUCLEAR MISSILES INTERCEPTED. 23 WARHEADS NEUTRALIZED IN FLIGHT.',
      newsHeadline: 'Nuclear strike fails',
      newsDetail: 'Missiles apparently destroyed before reaching targets. "They shot them down like flies."',
      importance: 'critical',
      effect: {
        locationId: 'usa-malmstrom',
        newStatus: 'targeted',
      },
    },
    {
      id: 'attack-silos-1',
      time: 11.5,
      type: 'destroy',
      locationId: 'usa-minot',
      alienMessage: 'RETALIATORY STRIKE: ELIMINATING NUCLEAR THREAT',
      newsHeadline: 'Minot AFB destroyed',
      newsDetail: 'Nuclear arsenal reportedly annihilated in precision strike.',
      importance: 'critical',
      focusCamera: true,
      effect: {
        locationId: 'usa-minot',
        newStatus: 'neutralized',
        newControlledBy: 'destroyed',
      },
    },
    {
      id: 'attack-silos-2',
      time: 12,
      type: 'destroy',
      locationId: 'usa-warren',
      alienMessage: 'SECONDARY NUCLEAR SITE: DESTROYED',
      newsHeadline: 'Warren AFB nuclear silos destroyed',
      newsDetail: 'Wyoming nuclear facility hit by kinetic rods.',
      importance: 'critical',
      effect: {
        locationId: 'usa-warren',
        newStatus: 'neutralized',
        newControlledBy: 'destroyed',
      },
    },
    {
      id: 'attack-silos-3',
      time: 12.5,
      type: 'destroy',
      locationId: 'usa-malmstrom',
      alienMessage: 'MONTANA NUCLEAR COMPLEX: ELIMINATED',
      newsHeadline: 'Malmstrom missile fields obliterated',
      newsDetail: 'America\'s ICBM capability effectively destroyed.',
      importance: 'critical',
      effect: {
        locationId: 'usa-malmstrom',
        newStatus: 'neutralized',
        newControlledBy: 'destroyed',
      },
    },
    {
      id: 'attack-silos-russia',
      time: 13,
      type: 'destroy',
      locationId: 'russia-kozelsk',
      alienMessage: 'RUSSIAN NUCLEAR ARSENAL: NEUTRALIZING',
      newsHeadline: 'Russian nuclear silos destroyed',
      newsDetail: 'Kozelsk ICBM base hit by sustained orbital bombardment.',
      importance: 'critical',
      effect: {
        locationId: 'russia-kozelsk',
        newStatus: 'neutralized',
        newControlledBy: 'destroyed',
      },
    },
    {
      id: 'attack-silos-china',
      time: 13.5,
      type: 'destroy',
      locationId: 'china-delingha',
      alienMessage: 'CHINESE NUCLEAR CAPABILITY: ELIMINATED',
      newsHeadline: 'Chinese nuclear missile base destroyed',
      newsDetail: 'Delingha facility in Qinghai province wiped out.',
      importance: 'critical',
      effect: {
        locationId: 'china-delingha',
        newStatus: 'neutralized',
        newControlledBy: 'destroyed',
      },
    },
    {
      id: 'attack-delhi',
      time: 14,
      type: 'attack',
      locationId: 'india-delhi',
      alienMessage: 'SOUTH ASIAN THEATER: SUPPRESSING DEFENSES',
      newsHeadline: 'New Delhi bombarded',
      newsDetail: 'Indian military command disrupted. Parliament building destroyed.',
      importance: 'major',
      effect: {
        locationId: 'india-delhi',
        newStatus: 'contested',
        stabilityChange: -35,
      },
    },
    {
      id: 'attack-islamabad',
      time: 14.5,
      type: 'attack',
      locationId: 'pakistan-islamabad',
      alienMessage: 'PAKISTANI NUCLEAR STATE: SECURING',
      newsHeadline: 'Islamabad under attack',
      newsDetail: 'Pakistani nuclear arsenal primary target. Government bunkers breached.',
      importance: 'major',
      effect: {
        locationId: 'pakistan-islamabad',
        newStatus: 'contested',
        stabilityChange: -40,
      },
    },

    // === HOUR 15-24: OCCUPATION BEGINS ===
    {
      id: 'occupy-1',
      time: 15,
      type: 'occupy',
      locationId: 'usa-newyork',
      alienMessage: 'INITIATING GROUND OCCUPATION: PRIMARY POPULATION CENTER',
      newsHeadline: 'Alien ground forces land in New York',
      newsDetail: 'Witnesses describe "metallic beings" emerging from landed craft. National Guard overwhelmed.',
      importance: 'critical',
      focusCamera: true,
      effect: {
        locationId: 'usa-newyork',
        newStatus: 'occupied',
        newControlledBy: 'alien',
        stabilityChange: -50,
      },
    },
    {
      id: 'attack-la',
      time: 16,
      type: 'attack',
      locationId: 'usa-losangeles',
      alienMessage: 'WEST COAST POPULATION CENTER: SOFTENING DEFENSES',
      newsHeadline: 'Los Angeles under orbital bombardment',
      newsDetail: 'Hollywood hills burning. LAX destroyed. Millions flee east.',
      importance: 'critical',
      focusCamera: true,
      effect: {
        locationId: 'usa-losangeles',
        newStatus: 'contested',
        stabilityChange: -30,
      },
    },
    {
      id: 'attack-power-russia',
      time: 17,
      type: 'destroy',
      locationId: 'russia-kursk',
      alienMessage: 'RUSSIAN POWER INFRASTRUCTURE: DISABLED',
      newsHeadline: 'Kursk nuclear plant destroyed',
      newsDetail: 'Radioactive contamination feared across western Russia.',
      importance: 'major',
      effect: {
        locationId: 'russia-kursk',
        newStatus: 'neutralized',
        newControlledBy: 'destroyed',
      },
    },
    {
      id: 'attack-kashiwazaki',
      time: 18,
      type: 'destroy',
      locationId: 'japan-kashiwazaki',
      alienMessage: 'JAPANESE POWER GRID: COLLAPSING',
      newsHeadline: 'Kashiwazaki nuclear plant hit',
      newsDetail: 'World\'s largest nuclear power plant destroyed. Japan faces total blackout.',
      importance: 'major',
      effect: {
        locationId: 'japan-kashiwazaki',
        newStatus: 'neutralized',
        newControlledBy: 'destroyed',
      },
    },
    {
      id: 'attack-tehran',
      time: 19,
      type: 'attack',
      locationId: 'iran-tehran',
      alienMessage: 'MIDDLE EAST: ELIMINATING REMAINING MILITARY CAPACITY',
      newsHeadline: 'Tehran struck by kinetic weapons',
      newsDetail: 'Iran\'s military installations targeted. Revolutionary Guard decimated.',
      importance: 'major',
      effect: {
        locationId: 'iran-tehran',
        newStatus: 'contested',
        stabilityChange: -30,
      },
    },
    {
      id: 'narrative-day1-end',
      time: 20,
      type: 'narrative',
      alienMessage: 'DAY ONE OBJECTIVES: 73% COMPLETE. RESISTANCE FRAGMENTING.',
      newsHeadline: 'Day of devastation ends with humanity reeling',
      newsDetail: 'Governments in disarray. Military command structures disrupted. Casualties estimated in millions.',
      importance: 'major',
    },
    {
      id: 'attack-mumbai',
      time: 21,
      type: 'attack',
      locationId: 'india-mumbai',
      alienMessage: 'INDIAN SUBCONTINENT: POPULATION CENTERS TARGETED',
      newsHeadline: 'Mumbai devastated',
      newsDetail: 'India\'s financial capital in ruins. Millions displaced.',
      importance: 'major',
      effect: {
        locationId: 'india-mumbai',
        newStatus: 'contested',
        stabilityChange: -25,
      },
    },
    {
      id: 'attack-saopaulo',
      time: 22,
      type: 'attack',
      locationId: 'brazil-saopaulo',
      alienMessage: 'SOUTH AMERICAN THEATER: COMMENCING OPERATIONS',
      newsHeadline: 'Sao Paulo under alien attack',
      newsDetail: 'South America\'s largest city bombarded from orbit.',
      importance: 'major',
      effect: {
        locationId: 'brazil-saopaulo',
        newStatus: 'contested',
        stabilityChange: -25,
      },
    },

    // === DAY 2: CONSOLIDATION ===
    {
      id: 'day2-start',
      time: 24,
      type: 'narrative',
      alienMessage: 'COMMENCING DAY TWO OPERATIONS',
      newsHeadline: 'Dawn breaks on a changed world',
      importance: 'minor',
    },
    {
      id: 'occupy-shanghai',
      time: 25,
      type: 'occupy',
      locationId: 'china-shanghai',
      alienMessage: 'ASIAN THEATER: SECURING ECONOMIC CENTER',
      newsHeadline: 'Shanghai occupied',
      newsDetail: 'Ground forces pour into China\'s largest city. Port seized.',
      importance: 'critical',
      effect: {
        locationId: 'china-shanghai',
        newStatus: 'occupied',
        newControlledBy: 'alien',
        stabilityChange: -40,
      },
    },
    {
      id: 'occupy-2',
      time: 26,
      type: 'occupy',
      locationId: 'china-beijing',
      alienMessage: 'ASIAN THEATER: SECURING POPULATION CENTER',
      newsHeadline: 'Beijing falls to alien forces',
      newsDetail: 'Chinese military resistance ends after 6-hour battle.',
      importance: 'critical',
      focusCamera: true,
      effect: {
        locationId: 'china-beijing',
        newStatus: 'occupied',
        newControlledBy: 'alien',
        stabilityChange: -60,
      },
    },
    {
      id: 'attack-ankara',
      time: 27,
      type: 'attack',
      locationId: 'turkey-ankara',
      alienMessage: 'NATO SOUTHERN FLANK: NEUTRALIZING',
      newsHeadline: 'Ankara bombarded',
      newsDetail: 'Turkey\'s capital struck. NATO\'s southern flank collapses.',
      importance: 'major',
      effect: {
        locationId: 'turkey-ankara',
        newStatus: 'contested',
        stabilityChange: -30,
      },
    },
    {
      id: 'attack-cairo',
      time: 28,
      type: 'attack',
      locationId: 'egypt-cairo',
      alienMessage: 'AFRICAN THEATER: BEGINNING OPERATIONS',
      newsHeadline: 'Cairo struck by orbital weapons',
      newsDetail: 'Egyptian military bases targeted. Pyramids damaged in blasts.',
      importance: 'major',
      effect: {
        locationId: 'egypt-cairo',
        newStatus: 'contested',
        stabilityChange: -25,
      },
    },
    {
      id: 'attack-rome',
      time: 29,
      type: 'attack',
      locationId: 'italy-rome',
      alienMessage: 'MEDITERRANEAN SECTOR: SECURING',
      newsHeadline: 'Rome under attack',
      newsDetail: 'Vatican City destroyed. Pope calls for prayers.',
      importance: 'major',
      effect: {
        locationId: 'italy-rome',
        newStatus: 'contested',
        stabilityChange: -20,
      },
    },
    {
      id: 'occupy-3',
      time: 30,
      type: 'occupy',
      locationId: 'russia-moscow',
      alienMessage: 'RUSSIAN SECTOR: OCCUPATION COMPLETE',
      newsHeadline: 'Moscow surrounded',
      newsDetail: 'Kremlin reportedly destroyed. Russian government status unknown.',
      importance: 'critical',
      focusCamera: true,
      effect: {
        locationId: 'russia-moscow',
        newStatus: 'occupied',
        newControlledBy: 'alien',
        stabilityChange: -70,
      },
    },
    {
      id: 'attack-pyongyang',
      time: 31,
      type: 'destroy',
      locationId: 'northkorea-pyongyang',
      alienMessage: 'ROGUE STATE: NEUTRALIZED PREEMPTIVELY',
      newsHeadline: 'Pyongyang obliterated',
      newsDetail: 'North Korean regime destroyed. Nuclear arsenal eliminated.',
      importance: 'major',
      effect: {
        locationId: 'northkorea-pyongyang',
        newStatus: 'neutralized',
        newControlledBy: 'destroyed',
      },
    },
    {
      id: 'attack-power-china',
      time: 32,
      type: 'destroy',
      locationId: 'china-yangjiang',
      alienMessage: 'CHINESE GRID: FINAL NODE ELIMINATED',
      newsHeadline: 'Yangjiang nuclear plant destroyed',
      newsDetail: 'China plunged into darkness as last major power station falls.',
      importance: 'major',
      effect: {
        locationId: 'china-yangjiang',
        newStatus: 'neutralized',
        newControlledBy: 'destroyed',
      },
    },
    {
      id: 'occupy-tokyo',
      time: 34,
      type: 'occupy',
      locationId: 'japan-tokyo',
      alienMessage: 'JAPANESE SECTOR: GROUND FORCES DEPLOYED',
      newsHeadline: 'Tokyo falls to alien occupation',
      newsDetail: 'Emperor broadcasts surrender message. Japanese resistance ends.',
      importance: 'critical',
      effect: {
        locationId: 'japan-tokyo',
        newStatus: 'occupied',
        newControlledBy: 'alien',
        stabilityChange: -50,
      },
    },

    // === DAY 2-3: GLOBAL SWEEP ===
    {
      id: 'resistance-forms',
      time: 36,
      type: 'human_response',
      alienMessage: 'DETECTING ORGANIZED RESISTANCE CELLS. MONITORING.',
      newsHeadline: 'Underground resistance movements forming',
      newsDetail: 'Encrypted communications suggest coordinated global response being organized.',
      importance: 'major',
    },
    {
      id: 'attack-jerusalem',
      time: 37,
      type: 'attack',
      locationId: 'israel-jerusalem',
      alienMessage: 'MIDDLE EAST: SECURING CONTESTED ZONE',
      newsHeadline: 'Jerusalem struck',
      newsDetail: 'Holy city bombarded. International outrage as sacred sites destroyed.',
      importance: 'critical',
      focusCamera: true,
      effect: {
        locationId: 'israel-jerusalem',
        newStatus: 'contested',
        stabilityChange: -40,
      },
    },
    {
      id: 'attack-brasilia',
      time: 38,
      type: 'attack',
      locationId: 'brazil-brasilia',
      alienMessage: 'SOUTH AMERICAN CAPITALS: TARGETING',
      newsHeadline: 'Brasilia under alien attack',
      newsDetail: 'Brazilian government buildings destroyed. Military scattered.',
      importance: 'major',
      effect: {
        locationId: 'brazil-brasilia',
        newStatus: 'contested',
        stabilityChange: -30,
      },
    },
    {
      id: 'attack-pretoria',
      time: 39,
      type: 'attack',
      locationId: 'southafrica-pretoria',
      alienMessage: 'AFRICAN CONTINENT: COMMENCING SWEEP',
      newsHeadline: 'South African capital targeted',
      newsDetail: 'Pretoria government district destroyed.',
      importance: 'minor',
      effect: {
        locationId: 'southafrica-pretoria',
        newStatus: 'contested',
        stabilityChange: -20,
      },
    },
    {
      id: 'occupy-washington',
      time: 40,
      type: 'occupy',
      locationId: 'usa-washington',
      alienMessage: 'PRIORITY OBJECTIVE ACHIEVED: US CAPITAL SECURED',
      newsHeadline: 'Washington D.C. falls',
      newsDetail: 'White House destroyed. President\'s fate unknown. Government reportedly relocated.',
      importance: 'critical',
      focusCamera: true,
      effect: {
        locationId: 'usa-washington',
        newStatus: 'occupied',
        newControlledBy: 'alien',
        stabilityChange: -80,
      },
    },
    {
      id: 'occupy-london',
      time: 42,
      type: 'occupy',
      locationId: 'uk-london',
      alienMessage: 'BRITISH ISLES: SECURED',
      newsHeadline: 'London falls to alien occupation',
      newsDetail: 'Buckingham Palace converted to alien command post.',
      importance: 'critical',
      effect: {
        locationId: 'uk-london',
        newStatus: 'occupied',
        newControlledBy: 'alien',
        stabilityChange: -50,
      },
    },
    {
      id: 'occupy-paris',
      time: 44,
      type: 'occupy',
      locationId: 'france-paris',
      alienMessage: 'FRENCH SECTOR: OCCUPATION COMPLETE',
      newsHeadline: 'Paris under alien control',
      newsDetail: 'French resistance fighters retreat to countryside.',
      importance: 'major',
      effect: {
        locationId: 'france-paris',
        newStatus: 'occupied',
        newControlledBy: 'alien',
        stabilityChange: -40,
      },
    },
    {
      id: 'attack-ottawa',
      time: 45,
      type: 'attack',
      locationId: 'canada-ottawa',
      alienMessage: 'NORTH AMERICAN SWEEP: CANADIAN SECTOR',
      newsHeadline: 'Ottawa attacked',
      newsDetail: 'Canadian Parliament Hill destroyed. PM evacuated to classified location.',
      importance: 'major',
      effect: {
        locationId: 'canada-ottawa',
        newStatus: 'contested',
        stabilityChange: -30,
      },
    },
    {
      id: 'attack-canberra',
      time: 46,
      type: 'attack',
      locationId: 'australia-canberra',
      alienMessage: 'OCEANIA: TARGETING GOVERNMENT CENTER',
      newsHeadline: 'Canberra struck from orbit',
      newsDetail: 'Australian government evacuated. Military in disarray.',
      importance: 'major',
      effect: {
        locationId: 'australia-canberra',
        newStatus: 'contested',
        stabilityChange: -25,
      },
    },

    // === HOUR 48-72: FINAL CONSOLIDATION ===
    {
      id: 'broadcast',
      time: 48,
      type: 'narrative',
      alienMessage: 'INITIATING POPULATION BROADCAST. COMPLIANCE INSTRUCTIONS TRANSMITTING.',
      newsHeadline: 'Alien broadcast reaches all devices worldwide',
      newsDetail: '"Resistance is inefficient. Integration is inevitable." Message repeating in all languages.',
      importance: 'critical',
    },
    {
      id: 'occupy-la',
      time: 50,
      type: 'occupy',
      locationId: 'usa-losangeles',
      alienMessage: 'WEST COAST: SECURED',
      newsHeadline: 'Los Angeles falls',
      newsDetail: 'Alien ground forces sweep through the city. Hollywood studios now alien barracks.',
      importance: 'major',
      effect: {
        locationId: 'usa-losangeles',
        newStatus: 'occupied',
        newControlledBy: 'alien',
        stabilityChange: -30,
      },
    },
    {
      id: 'occupy-delhi',
      time: 52,
      type: 'occupy',
      locationId: 'india-delhi',
      alienMessage: 'INDIAN SUBCONTINENT: OCCUPATION PROCEEDING',
      newsHeadline: 'New Delhi falls to alien forces',
      newsDetail: 'India\'s capital under full alien control. 1.4 billion now under occupation.',
      importance: 'critical',
      focusCamera: true,
      effect: {
        locationId: 'india-delhi',
        newStatus: 'occupied',
        newControlledBy: 'alien',
        stabilityChange: -50,
      },
    },
    {
      id: 'occupy-seoul',
      time: 54,
      type: 'occupy',
      locationId: 'southkorea-seoul',
      alienMessage: 'KOREAN PENINSULA: FULLY SECURED',
      newsHeadline: 'Seoul occupied',
      newsDetail: 'Korean peninsula unified under alien control.',
      importance: 'major',
      effect: {
        locationId: 'southkorea-seoul',
        newStatus: 'occupied',
        newControlledBy: 'alien',
        stabilityChange: -40,
      },
    },
    {
      id: 'day3-morning',
      time: 56,
      type: 'narrative',
      alienMessage: 'GLOBAL PACIFICATION: 87% COMPLETE',
      newsHeadline: 'Third day of invasion begins',
      newsDetail: 'Isolated pockets of resistance remain. Major cities under alien control.',
      importance: 'major',
    },
    {
      id: 'attack-lourdes',
      time: 58,
      type: 'destroy',
      locationId: 'russia-lourdes',
      alienMessage: 'REMAINING SURVEILLANCE ASSETS: ELIMINATING',
      newsHeadline: 'Russian listening post destroyed',
      importance: 'minor',
      effect: {
        locationId: 'russia-lourdes',
        newStatus: 'neutralized',
        newControlledBy: 'destroyed',
      },
    },
    {
      id: 'occupy-berlin',
      time: 60,
      type: 'occupy',
      locationId: 'germany-berlin',
      alienMessage: 'CENTRAL EUROPE: SECURED',
      newsHeadline: 'Berlin under alien control',
      newsDetail: 'Germany surrenders. EU ceases to function as governing body.',
      importance: 'major',
      effect: {
        locationId: 'germany-berlin',
        newStatus: 'occupied',
        newControlledBy: 'alien',
        stabilityChange: -40,
      },
    },
    {
      id: 'occupy-rome',
      time: 62,
      type: 'occupy',
      locationId: 'italy-rome',
      alienMessage: 'MEDITERRANEAN: FINAL RESISTANCE CRUSHED',
      newsHeadline: 'Rome occupied',
      newsDetail: 'Italian resistance collapses. Pope broadcasts surrender plea from hiding.',
      importance: 'major',
      effect: {
        locationId: 'italy-rome',
        newStatus: 'occupied',
        newControlledBy: 'alien',
        stabilityChange: -30,
      },
    },
    {
      id: 'final-resistance',
      time: 66,
      type: 'human_response',
      alienMessage: 'SCATTERED RESISTANCE DETECTED. DISPATCHING SUPPRESSION UNITS.',
      newsHeadline: 'Last organized military resistance in Swiss Alps',
      newsDetail: 'Coalition of surviving military units makes final stand. Outcome uncertain.',
      importance: 'major',
    },
    {
      id: 'scenario-end',
      time: 72,
      type: 'narrative',
      alienMessage: 'PHASE ONE COMPLETE. PREPARING PHASE TWO: RESOURCE EXTRACTION.',
      newsHeadline: 'The new world order takes shape',
      newsDetail: 'As Day Three ends, humanity faces an uncertain future under alien dominion.',
      importance: 'critical',
    },
  ],
};
